<Project>
  <PropertyGroup>
    <Version>1.0.1</Version>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS8669;RS2008;CS1591</NoWarn>
    <Authors>Jose Sagasta, HybridCache.Plus Contributors</Authors>
    <Company>Jose Sagasta</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/sagasta/HybridCachePlus</RepositoryUrl>
    <PackageProjectUrl>https://github.com/sagasta/HybridCachePlus</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="$(MSBuildThisFileDirectory)assets\icon.png" Pack="true" PackagePath="\" Visible="false" Condition="Exists('$(MSBuildThisFileDirectory)assets\icon.png')" />
  </ItemGroup>
</Project>
