using AspirePlayground.Api;
using HybridCache.Plus;
using HybridCache.Plus.Tenancy;
using Microsoft.AspNetCore.Mvc;
using Scalar.AspNetCore;

var builder = WebApplication.CreateBuilder(args);

// Add OpenAPI & Scalar
builder.Services.AddOpenApi();

// Add OpenTelemetry and register HybridCache.Plus meter
builder.Services.AddOpenTelemetry()
    .WithMetrics(metrics =>
    {
        metrics.AddMeter(HybridCache.Plus.Diagnostics.HybridCachePlusDiagnostics.MeterName);
    });

// Node identifier (passed from Aspire AppHost)
var nodeId = Environment.GetEnvironmentVariable("NODE_ID") ?? "Node-Local";

// 1. HybridCache core
builder.Services.AddHybridCache();

var enableBackplane = builder.Configuration.GetValue<bool>("ENABLE_BACKPLANE", true);
var enableMultiTenant = builder.Configuration.GetValue<bool>("ENABLE_MULTITENANT", true);

// 2. HybridCache.Plus setup
builder.Services.AddHybridCachePlus(plus =>
{
    // Redis Backplane for L1 eviction across instances
    var backplaneConn = builder.Configuration.GetConnectionString("redis-backplane");
    if (enableBackplane && !string.IsNullOrEmpty(backplaneConn))
    {
        plus.UseRedisBackplane(opts =>
        {
            opts.Configuration = backplaneConn;
            opts.ChannelName = "hybridcache:playground:evictions";
        });
    }

    // Multi-Tenant Redis L2 Router
    if (enableMultiTenant)
    {
        plus.UseMultiTenantRedisL2(tenancy =>
        {
            tenancy.ResolveConnectionString(tenantId =>
            {
                return tenantId?.ToLowerInvariant() switch
                {
                    "tenant_alpha" or "alpha" => builder.Configuration.GetConnectionString("redis-tenant-alpha"),
                    "tenant_beta" or "beta" => builder.Configuration.GetConnectionString("redis-tenant-beta"),
                    _ => builder.Configuration.GetConnectionString("redis-tenant-alpha")
                };
            });
            tenancy.EnableKeyPrefixTenantExtraction = true;
        });
    }
});

// Single-Tenant Redis L2 fallback when multi-tenancy is disabled
if (!enableMultiTenant)
{
    var sharedConn = builder.Configuration.GetConnectionString("redis-shared");
    if (!string.IsNullOrEmpty(sharedConn))
    {
        builder.Services.AddStackExchangeRedisCache(options =>
        {
            options.Configuration = sharedConn;
            options.InstanceName = "shared:";
        });
    }
}

// 3. Register ProductRepository and Decorate with generated decorator
builder.Services.AddSingleton<ProductRepository>();
builder.Services.AddSingleton<IProductRepository>(sp => sp.GetRequiredService<ProductRepository>());
builder.Services.DecorateProductRepositoryWithCache();

var app = builder.Build();

app.MapOpenApi();
app.MapScalarApiReference();

app.MapGet("/", () => Results.Redirect("/scalar/v1"));

// ENDPOINTS

// 1. GET /api/products/{tenantId}/{productId}
// Uses ICatalogCache extension method generated on HybridCache
app.MapGet("/api/products/{tenantId}/{productId:long}", async (
    string tenantId,
    long productId,
    Microsoft.Extensions.Caching.Hybrid.HybridCache cache,
    ProductRepository dbRepo) =>
{
    var beforeCount = ProductRepository.TotalDbQueries;
    var startTime = System.Diagnostics.Stopwatch.GetTimestamp();

    // Call strongly-typed cache extension method generated by HybridCachePlus
    var product = await cache.GetProductAsync(tenantId, productId, async ct =>
    {
        var dbItem = await dbRepo.GetByIdAsync(tenantId, productId, ct);
        return dbItem!;
    });

    var elapsed = System.Diagnostics.Stopwatch.GetElapsedTime(startTime);
    var afterCount = ProductRepository.TotalDbQueries;
    var isCacheMiss = afterCount > beforeCount;

    return Results.Ok(new
    {
        Node = nodeId,
        TenantId = tenantId,
        ProductId = productId,
        Source = isCacheMiss ? "MISS (Loaded from SQLite Database)" : "HIT (Retrieved from HybridCache L1/L2)",
        Latency = $"{elapsed.TotalMilliseconds:F2} ms",
        TotalDbQueriesAcrossAllCalls = afterCount,
        Product = product
    });
})
.WithName("GetProduct")
.WithSummary("Reads a product from HybridCache (or executes factory DB query on miss).");

// 2. PUT /api/products/{tenantId}/{productId}
// Calls repo.UpdateProductAsync(...) on IProductRepository
// This executes the GENERATED DECORATOR, which mutates DB, purges cache key, and publishes eviction to Backplane!
app.MapPut("/api/products/{tenantId}/{productId:long}", async (
    string tenantId,
    long productId,
    [FromBody] UpdateProductRequest request,
    IProductRepository repo) =>
{
    var updated = await repo.UpdateProductAsync(tenantId, productId, request.Name, request.Price);

    return Results.Ok(new
    {
        Node = nodeId,
        Action = "Mutated via IProductRepository decorator",
        CacheEviction = "Key invalidated locally and eviction message published to Redis Backplane",
        UpdatedProduct = updated
    });
})
.WithName("UpdateProduct")
.WithSummary("Updates product via Decorator: purges cache key and broadcasts eviction across all nodes.");

// 3. DELETE /api/products/{tenantId}/{productId}
app.MapDelete("/api/products/{tenantId}/{productId:long}", async (
    string tenantId,
    long productId,
    IProductRepository repo) =>
{
    var deleted = await repo.DeleteProductAsync(tenantId, productId);
    return Results.Ok(new
    {
        Node = nodeId,
        Deleted = deleted,
        Action = "Deleted via IProductRepository decorator (cache evicted)"
    });
})
.WithName("DeleteProduct")
.WithSummary("Deletes product via Decorator: purges cache key and broadcasts eviction across all nodes.");

// 4. POST /api/products/query (CQRS Query)
app.MapPost("/api/products/query", async (
    [FromBody] GetProductQuery query,
    Microsoft.Extensions.Caching.Hybrid.HybridCache cache,
    ProductRepository dbRepo) =>
{
    var beforeCount = ProductRepository.TotalDbQueries;
    var startTime = System.Diagnostics.Stopwatch.GetTimestamp();

    var product = await cache.GetProductByQueryAsync(query, async ct =>
    {
        var dbItem = await dbRepo.GetByIdAsync(query.TenantId, query.ProductId, ct);
        return dbItem!;
    });

    var elapsed = System.Diagnostics.Stopwatch.GetElapsedTime(startTime);
    var afterCount = ProductRepository.TotalDbQueries;
    var isCacheMiss = afterCount > beforeCount;

    return Results.Ok(new
    {
        Node = nodeId,
        TenantId = query.TenantId,
        ProductId = query.ProductId,
        Source = isCacheMiss ? "MISS (Loaded from SQLite Database)" : "HIT (Retrieved from HybridCache L1/L2)",
        Latency = $"{elapsed.TotalMilliseconds:F2} ms",
        TotalDbQueriesAcrossAllCalls = afterCount,
        Product = product
    });
})
.WithName("GetProductByQuery")
.WithSummary("CQRS Query: reads product using complex object parameter query.");

// 5. POST /api/products/command (CQRS Command)
app.MapPost("/api/products/command", async (
    [FromBody] UpdateProductCommand command,
    IProductRepository repo) =>
{
    var updated = await repo.UpdateWithCommandAsync(command);

    return Results.Ok(new
    {
        Node = nodeId,
        Action = "Mutated via CQRS command on decorated IProductRepository",
        CacheEviction = "Key invalidated locally and eviction message published to Redis Backplane",
        UpdatedProduct = updated
    });
})
.WithName("UpdateProductWithCommand")
.WithSummary("CQRS Command: updates product via command decorator and invalidates cache.");

// 6. POST /api/products/evict-tenant-tag/{tenantId}
app.MapPost("/api/products/evict-tenant-tag/{tenantId}", async (
    string tenantId,
    Microsoft.Extensions.Caching.Hybrid.HybridCache cache) =>
{
    await cache.EvictProductByTenantIdTagAsync(tenantId);
    return Results.Ok(new
    {
        Node = nodeId,
        TenantId = tenantId,
        Action = $"Evicted entire tag tenant:{tenantId} locally and published to Redis Backplane"
    });
})
.WithName("EvictTenantTag")
.WithSummary("Evicts all products with tag tenant:{tenantId} across all nodes via Redis backplane.");

// 7. POST /api/system/reset-db-counter
app.MapPost("/api/system/reset-db-counter", () =>
{
    ProductRepository.ResetQueryCount();
    return Results.Ok(new { Message = "Database query counter reset to 0" });
})
.WithName("ResetDbCounter")
.WithSummary("Resets the internal SQLite query counter for clean E2E test assertions.");

// 7. GET /api/system/status
app.MapGet("/api/system/status", (IConfiguration config) =>
{
    return Results.Ok(new
    {
        Node = nodeId,
        ProcessId = Environment.ProcessId,
        Machine = Environment.MachineName,
        TotalDbQueries = ProductRepository.TotalDbQueries,
        EnableBackplane = enableBackplane,
        EnableMultiTenant = enableMultiTenant,
        RedisBackplaneConfigured = !string.IsNullOrEmpty(config.GetConnectionString("redis-backplane")),
        RedisSharedConfigured = !string.IsNullOrEmpty(config.GetConnectionString("redis-shared")),
        RedisTenantAlphaConfigured = !string.IsNullOrEmpty(config.GetConnectionString("redis-tenant-alpha")),
        RedisTenantBetaConfigured = !string.IsNullOrEmpty(config.GetConnectionString("redis-tenant-beta")),
        AvailableTenants = new[] { "tenant_alpha", "tenant_beta" }
    });
})
.WithName("GetSystemStatus");

app.Run();

public record UpdateProductRequest(string Name, decimal Price);
