using System.Text;
using HybridCache.Plus.Generators.Models;

namespace HybridCache.Plus.Generators.Emitters;

public static class DecoratorEmitter
{
    public static string Emit(DecoratorInterfaceModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.Caching.Hybrid;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.InterfaceNamespace))
        {
            sb.AppendLine($"namespace {model.InterfaceNamespace}");
            sb.AppendLine("{");
        }

        var indent = string.IsNullOrEmpty(model.InterfaceNamespace) ? "" : "    ";

        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// Automatic cache invalidation decorator for <see cref=\"{model.InterfaceName}\"/> generated by HybridCache.Plus.");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}public sealed class {model.DecoratorClassName} : {model.InterfaceFullName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    private readonly {model.InterfaceFullName} _inner;");
        sb.AppendLine($"{indent}    private readonly global::Microsoft.Extensions.Caching.Hybrid.HybridCache _cache;");
        sb.AppendLine($"{indent}    private readonly global::HybridCache.Plus.Backplane.IEvictionPublisher? _publisher;");
        sb.AppendLine();
        sb.AppendLine($"{indent}    public {model.DecoratorClassName}(");
        sb.AppendLine($"{indent}        {model.InterfaceFullName} inner,");
        sb.AppendLine($"{indent}        global::Microsoft.Extensions.Caching.Hybrid.HybridCache cache,");
        sb.AppendLine($"{indent}        global::HybridCache.Plus.Backplane.IEvictionPublisher? publisher = null)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        _inner = inner ?? throw new ArgumentNullException(nameof(inner));");
        sb.AppendLine($"{indent}        _cache = cache ?? throw new ArgumentNullException(nameof(cache));");
        sb.AppendLine($"{indent}        _publisher = publisher;");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        foreach (var method in model.Methods)
        {
            EmitMethod(sb, indent + "    ", method);
        }

        sb.AppendLine($"{indent}}}");

        if (!string.IsNullOrEmpty(model.InterfaceNamespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, string indent, DecoratorMethodModel method)
    {
        var paramList = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
        var argList = string.Join(", ", method.Parameters.Select(p => p.Name));
        var ctParam = method.Parameters.FirstOrDefault(p => p.IsCancellationToken);
        var ctName = ctParam != null ? ctParam.Name : "default";

        // If no evictions, just forward directly
        if (method.EvictionActions.Count == 0)
        {
            sb.AppendLine($"{indent}public {method.ReturnType} {method.MethodName}({paramList})");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine(method.ReturnsVoid
                ? $"{indent}    _inner.{method.MethodName}({argList});"
                : $"{indent}    return _inner.{method.MethodName}({argList});");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
            return;
        }

        // Method has evictions: execute inner, then invalidate
        if (method.IsAsync)
        {
            sb.AppendLine($"{indent}public async {method.ReturnType} {method.MethodName}({paramList})");
            sb.AppendLine($"{indent}{{");

            sb.AppendLine(method.IsGenericTask
                ? $"{indent}    var result = await _inner.{method.MethodName}({argList}).ConfigureAwait(false);"
                : $"{indent}    await _inner.{method.MethodName}({argList}).ConfigureAwait(false);");

            sb.AppendLine();
            sb.AppendLine($"{indent}    // Automated cache invalidation via HybridCache.Plus");
            foreach (var eviction in method.EvictionActions)
            {
                if (!string.IsNullOrEmpty(eviction.KeyTemplate))
                {
                    sb.AppendLine($"{indent}    await _cache.RemoveAsync($\"{eviction.KeyTemplate}\", {ctName}).ConfigureAwait(false);");
                    sb.AppendLine($"{indent}    global::HybridCache.Plus.Diagnostics.HybridCachePlusDiagnostics.RecordEviction($\"{eviction.KeyTemplate}\", \"DecoratorMutation\");");
                    sb.AppendLine($"{indent}    if (_publisher != null)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        await _publisher.PublishAsync(global::HybridCache.Plus.Backplane.BackplaneEvictionMessage.CreateKey($\"{eviction.KeyTemplate}\"), {ctName}).ConfigureAwait(false);");
                    sb.AppendLine($"{indent}    }}");
                }
                foreach (var tag in eviction.TagTemplates)
                {
                    sb.AppendLine($"{indent}    await _cache.RemoveByTagAsync($\"{tag}\", {ctName}).ConfigureAwait(false);");
                    sb.AppendLine($"{indent}    global::HybridCache.Plus.Diagnostics.HybridCachePlusDiagnostics.RecordEviction($\"{tag}\", \"DecoratorTagMutation\");");
                    sb.AppendLine($"{indent}    if (_publisher != null)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        await _publisher.PublishAsync(global::HybridCache.Plus.Backplane.BackplaneEvictionMessage.CreateTag($\"{tag}\"), {ctName}).ConfigureAwait(false);");
                    sb.AppendLine($"{indent}    }}");
                }
            }

            if (method.IsGenericTask)
            {
                sb.AppendLine();
                sb.AppendLine($"{indent}    return result;");
            }

            sb.AppendLine($"{indent}}}");
        }
        else
        {
            sb.AppendLine($"{indent}public {method.ReturnType} {method.MethodName}({paramList})");
            sb.AppendLine($"{indent}{{");

            if (method.ReturnsVoid)
            {
                sb.AppendLine($"{indent}    _inner.{method.MethodName}({argList});");
            }
            else
            {
                sb.AppendLine($"{indent}    var result = _inner.{method.MethodName}({argList});");
            }

            sb.AppendLine();
            sb.AppendLine($"{indent}    // Automated synchronous cache invalidation via HybridCache.Plus");
            foreach (var eviction in method.EvictionActions)
            {
                if (!string.IsNullOrEmpty(eviction.KeyTemplate))
                {
                    sb.AppendLine($"{indent}    _cache.RemoveAsync($\"{eviction.KeyTemplate}\", {ctName}).AsTask().GetAwaiter().GetResult();");
                    sb.AppendLine($"{indent}    global::HybridCache.Plus.Diagnostics.HybridCachePlusDiagnostics.RecordEviction($\"{eviction.KeyTemplate}\", \"DecoratorMutation\");");
                    sb.AppendLine($"{indent}    if (_publisher != null)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        _publisher.PublishAsync(global::HybridCache.Plus.Backplane.BackplaneEvictionMessage.CreateKey($\"{eviction.KeyTemplate}\"), {ctName}).AsTask().GetAwaiter().GetResult();");
                    sb.AppendLine($"{indent}    }}");
                }
                foreach (var tag in eviction.TagTemplates)
                {
                    sb.AppendLine($"{indent}    _cache.RemoveByTagAsync($\"{tag}\", {ctName}).AsTask().GetAwaiter().GetResult();");
                    sb.AppendLine($"{indent}    global::HybridCache.Plus.Diagnostics.HybridCachePlusDiagnostics.RecordEviction($\"{tag}\", \"DecoratorTagMutation\");");
                    sb.AppendLine($"{indent}    if (_publisher != null)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        _publisher.PublishAsync(global::HybridCache.Plus.Backplane.BackplaneEvictionMessage.CreateTag($\"{tag}\"), {ctName}).AsTask().GetAwaiter().GetResult();");
                    sb.AppendLine($"{indent}    }}");
                }
            }

            if (!method.ReturnsVoid)
            {
                sb.AppendLine();
                sb.AppendLine($"{indent}    return result;");
            }

            sb.AppendLine($"{indent}}}");
        }

        sb.AppendLine();
    }
}
